stages:
  - tagging

agileflow:
  stage: tagging
  script:
    - chmod +x ./agileflow # Make sure the script has execution permissions
    - ./agileflow --key ${AGILEFLOW_KEY} # Run the script with the key so the tag can be pushed
  only:
    - /^release\/[0-9]+\.[0-9]+$/
    - /^r\/[0-9]+\.[0-9]+$/
