include:
  - local: templates/AgileFlow.gitlab-ci.yml

release:
  stage: deploy
  needs: ["agileflow"] 
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${VERSION}"
      --customPlatform "linux/amd64"
      --build-arg TARGETOS=linux
      --build-arg TARGETARCH=amd64