#!/bin/bash
# 
# MIT License
# 
# Copyright (c) 2024 LKMX Software Development S de RL de CV - https://lkmx.io
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# AgileFlow
# A simple tool to automate the release process in Git repositories.
# https://code.logickernel.com/kernel/agileflow

VERSION=

# Function to display usage
usage() {
    echo "usage: $0 <command> [<args>]"
    echo
    echo "These are AgileFlow commands used in common situations:"
    echo
    echo "  install     Install AgileFlow in the current project"
    echo "  release     Create a new release branch"
    echo "  tag         Tag the current commit with the next version"
    echo "  version     Display the version of AgileFlow"
    echo
    echo "For more information, see https://code.logickernel.com/kernel/agileflow"
    exit 1
}

get_branch_name() {
    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    if [[ "$BRANCH_NAME" == "HEAD" || -z "$BRANCH_NAME" ]]; then
        if [[ -n "$CI_COMMIT_REF_NAME" ]]; then
            BRANCH_NAME="$CI_COMMIT_REF_NAME"
        elif [[ -n "$GITHUB_REF_NAME" ]]; then
            BRANCH_NAME="$GITHUB_REF_NAME"
        elif [[ -n "$GITHUB_REF" ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        else
            echo "[ERROR] Unable to determine branch name."
            exit 1
        fi
    fi
}

check_latest_release() {
    if [[ -z "$BRANCH_NAME" ]]; then
        get_branch_name
    fi
    # Obtain the list of branches from the remote repository starting with 'release/'
    REMOTE_BRANCHES=$(git branch -r | grep -E "^ *origin/release/[0-9]+\.[0-9]+$" | sed -E 's| *origin/||')

    # Sort the branches
    SORTED_BRANCHES=$(echo "$REMOTE_BRANCHES" | sort -V)

    # If DEBUG is enabled, print the sorted branches
    if $DEBUG; then
        echo "[DEBUG] Sorted branches:"
        echo $SORTED_BRANCHES
        echo
    fi

    # Get the latest branch
    LATEST_BRANCH=$(echo "$SORTED_BRANCHES" | tail -n 1)

    # If DEBUG is enabled, print the latest branch
    if $DEBUG; then
        echo "[DEBUG] Latest branch:"
        echo $LATEST_BRANCH
        echo
    fi

    # Check if the current branch is the latest release branch
    if [[ "$BRANCH_NAME" == "$LATEST_BRANCH" ]]; then
        IS_LATEST_RELEASE=true
    else
        IS_LATEST_RELEASE=false
    fi
}

# Function to handle 'install' command
install_command() {
    CI_CD_ENGINE=""

    # Parse the CI/CD engine flag
    while [[ $# -gt 0 ]]; do
        case $1 in
            --gitlab)
                CI_CD_ENGINE="GitLab"
                shift
                ;;
            --github)
                CI_CD_ENGINE="GitHub"
                shift
                ;;
            --generate)
                CI_CD_ENGINE="None"
                shift
                ;;
            *)
                usage
                ;;
        esac
    done

    # If no flag is passed, prompt the user to select the CI/CD engine
    if [[ -z "$CI_CD_ENGINE" ]]; then
        echo "Select your CI/CD engine:"
        echo "  1) GitLab"
        echo "  2) GitHub"
        read -p "Enter choice [1-2]: " choice
        case $choice in
            1)
                CI_CD_ENGINE="GitLab"
                ;;
            2)
                CI_CD_ENGINE="GitHub"
                ;;
            *)
                echo "[ERROR] Invalid choice."
                exit 1
                ;;
        esac
    fi

    # Create temporary directory and generate SSH key pair
    TEMP_DIR=$(mktemp -d)
    ssh-keygen -t ed25519 -C "agileflow-deploy-key" -f "$TEMP_DIR/agileflow-deploy-key" -N "" >/dev/null 2>&1
    
    case $CI_CD_ENGINE in
        GitLab)
            echo "Follow these steps to add the deploy key to your GitLab repository:"
            echo "  1) Go to your project's Settings > Repository > Deploy keys"
            echo "  2) Add the generated public key as a deploy key making sure to grant it write permissions:"
            echo
            echo "$(cat "$TEMP_DIR/agileflow-deploy-key.pub")"
            echo
            echo "  3) Go to your project's Settings > CI/CD > Variables"
            echo "  4) Add a new variable of type File, key AGILEFLOW_KEY and as value the generated private key:"
            echo
            echo "$(cat "$TEMP_DIR/agileflow-deploy-key")"
            echo
            echo "  It is recommended to protect the variable so that it's only available in pipelines controlled by an authorized user"
            echo

            # Add GitLab CI/CD configuration to automatically tag releases
            if ! grep -q "agileflow:" .gitlab-ci.yml; then
                echo "agileflow:" >> .gitlab-ci.yml
                echo "  stage: deploy" >> .gitlab-ci.yml
                echo "  script:" >> .gitlab-ci.yml
                echo "    - ./agileflow tag --key \${AGILEFLOW_KEY}" >> .gitlab-ci.yml
                echo "  only:" >> .gitlab-ci.yml
                echo "    - /^release\/[0-9]+\\.[0-9]+\$/" >> .gitlab-ci.yml
                echo ".gitlab-ci.yml updated with AgileFlow configuration."
            else
                echo ".gitlab-ci.yml already contains AgileFlow configuration. No changes were made."
            fi
            
            ;;
        GitHub)
            # Display instructions for GitHub similar to GitLab's instructions but using base64 < "$TEMP_DIR/agileflow-deploy-key" instead of cat for the private key since GitHub doesn't support file type CD/CI variables
            echo "Follow these steps to add the deploy key to your GitHub repository:"
            echo "  1) Go to your repository's settings"
            echo "  2) Add the public key below as a deploy key:"
            echo
            echo "$(cat "$TEMP_DIR/agileflow-deploy-key.pub")"
            echo
            echo "  3) Go to your repository's settings > Secrets"
            echo "  4) Add a new secret called AGILEFLOW_KEY and paste the private key below:"
            echo
            echo "$(base64 < "$TEMP_DIR/agileflow-deploy-key")"
            echo
            ;;

        None)
            echo "Public key:"
            echo "$(cat "$TEMP_DIR/agileflow-deploy-key.pub")"
            echo
            echo "Private key:"
            echo "$(cat "$TEMP_DIR/agileflow-deploy-key")"
            ;;
    esac

    rm -rf "$TEMP_DIR"
    exit 0
}

release_command() {
    # git fetch all and prune the deleted branches
    git fetch --all --prune

    MAJOR_RELEASE=false
    DRY_RUN=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            --major)
                MAJOR_RELEASE=true
                ;;
            --dry-run)
                DRY_RUN=true
                ;;
            *)
                usage
                exit 1
                ;;
        esac
        shift
    done

    get_branch_name

    VERSION="${BRANCH_NAME#*/}"
    MAJOR=$(echo "$VERSION" | cut -d. -f1)
    MINOR=$(echo "$VERSION" | cut -d. -f2)

    if $MAJOR_RELEASE; then
        MAJOR=$((MAJOR + 1))
        MINOR=0
    else
        if ! [[ "$MAJOR" =~ ^[0-9]+$ ]]; then
            MAJOR=0
        fi
        MINOR=$((MINOR + 1))
    fi

    NEXT_RELEASE="release/$MAJOR.$MINOR"

    # Obtain the list of branches from the remote repository starting with 'release/'
    REMOTE_BRANCHES=$(git branch -r | grep -E "^ *origin/release/[0-9]+\.[0-9]+$" | sed -E 's| *origin/||')


    if git show-ref --verify --quiet "refs/heads/$NEXT_RELEASE"; then
        echo "[ERROR] Release branch '$NEXT_RELEASE' already exists."
        exit 1
    fi

    if $DRY_RUN; then
        echo "$NEXT_RELEASE"
        exit 0
    fi

    git checkout -b "$NEXT_RELEASE"
    git push origin "$NEXT_RELEASE" --set-upstream || exit 1
    echo "[INFO] Pushed release branch: $NEXT_RELEASE"
}

# Function to handle 'tag' command
tag_command() {
    # git fetch all and prune the deleted branches
    git fetch --all --prune

    TEMP_DIR=$(mktemp -d)

    # Parse arguments
    PRIVATE_KEY=""
    DRY_RUN=false
    SKIP_MAIN=false
    DEBUG=false
    while [[ $# -gt 0 ]]; do
        case $1 in
            --key)
                PRIVATE_KEY="$2"
                shift 2
                ;;
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --skip-main)
                SKIP_MAIN=true
                shift
                ;;
            --debug)
                DEBUG=true
                shift
                ;;
            *)
                usage
                ;;
        esac
    done

    # Handle private key if provided
    if [[ -n "$PRIVATE_KEY" ]]; then
        echo "[INFO] Validating private key..."
        if [[ ! -f "$PRIVATE_KEY" ]]; then
            echo "[INFO] Provided key is not a file, trying to decode as base64..."
            echo "$PRIVATE_KEY" | base64 -d > "$TEMP_DIR/deploy_key" 2>/dev/null
            if [[ $? -ne 0 ]]; then
                echo "[ERROR] Invalid file or base64-encoded key."
                rm -rf "$TEMP_DIR"
                exit 1
            fi
            chmod 600 "$TEMP_DIR/deploy_key"
            DEPLOY_KEY_PATH="$TEMP_DIR/deploy_key"
        else
            chmod 600 "$PRIVATE_KEY"
            DEPLOY_KEY_PATH="$PRIVATE_KEY"
        fi
        export GIT_SSH_COMMAND="ssh -i $DEPLOY_KEY_PATH -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"

        # Convert remote URL to SSH if a private key is provided
        REMOTE_URL=$(git remote get-url origin)
        if [[ "$REMOTE_URL" =~ ^https:// ]]; then
            SSH_URL=$(echo "$REMOTE_URL" | sed -E 's|https://[^@]+@([^/]+)/(.+)|git@\1:\2|')
            SSH_URL="${SSH_URL%.git}.git"
            git remote set-url origin "$SSH_URL"
            echo "[INFO] Converted remote URL to SSH: $SSH_URL"
        fi
    fi

    get_branch_name
    check_latest_release

    if [[ ! "$BRANCH_NAME" =~ ^release/[0-9]+\.[0-9]+$ ]]; then
        echo "[ERROR] Release branch not detected. Branch name '$BRANCH_NAME' does not match 'r/X.Y' or 'release/X.Y'."
        rm -rf "$TEMP_DIR"
        exit 1
    fi

    VERSION="${BRANCH_NAME#*/}"
    LATEST_TAG=$(git tag --list "v$VERSION.*" --sort=-v:refname | head -n 1)

    if [[ -z "$LATEST_TAG" ]]; then
        NEXT_VERSION="v${VERSION}.0"
    else
        NEXT_VERSION=$(echo "$LATEST_TAG" | awk -F. -v OFS=. '{$NF+=1; print}')
    fi

    if $DRY_RUN; then
        echo "$NEXT_VERSION"
        if ! $SKIP_MAIN && $IS_LATEST_RELEASE; then
            echo "* It will be merged into main."
        fi
        exit 0
    fi

    git tag "$NEXT_VERSION"
    git push origin "$NEXT_VERSION"

    if [[ $? -ne 0 ]]; then
        echo "[ERROR] Failed to push tag."
        rm -rf "$TEMP_DIR"
        exit 1
    fi

    echo "[INFO] Successfully tagged and pushed: $NEXT_VERSION"


    if $IS_LATEST_RELEASE; then
        echo "[INFO] This is the latest release branch. Merging tag to main branch..."
        git checkout main
        git pull origin main

        # Merge the tag to main branch with fast-forward
        git merge --ff-only "$NEXT_VERSION"
        # If the merge failed, exit with an error
        if [[ $? -ne 0 ]]; then
            echo "[ERROR] Failed to merge tag to main branch. Merge manually or try the --skip-main flag."
            rm -rf "$TEMP_DIR"
            exit 1
        fi
        git push origin main
        echo "[INFO] Merged tag to main branch."
    else
        echo "[INFO] This is not the latest release branch. The latest release branch is '$LATEST_BRANCH'."
    fi

    rm -rf "$TEMP_DIR"
}

# Main entry point
if [[ $# -lt 1 ]]; then
    usage
fi

COMMAND="$1"
shift

case "$COMMAND" in
    install)
        install_command "$@"
        ;;
    release)
        release_command "$@"
        ;;
    tag)
        tag_command "$@"
        ;;
    version)
        version_command "$@"
        ;;
    *)
        usage
        ;;
esac