stages:
  - version
  - build
  - test
  - deploy
  - cleanup

agileflow:
  stage: version
  image: registry.logickernel.com/kernel/agileflow:0.6.67
  script:
    - agileflow gitlab-ci
  artifacts:
    reports:
      dotenv: VERSION