name: Tag Version

on:
  push:
    branches:
      - "release/*"

jobs:
  tag_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install AgileFlow
        run: ./agileflow tag --key ${{ secrets.AGILEFLOW_KEY }} --yes
