name: Publish Agileflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Prepare versioned release script
        run: sed "s/AGILEFLOW_VERSION=.*/AGILEFLOW_VERSION=${VERSION}/" agileflow

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: agileflow
